### ISSUE TITLE
Problem with SVG image containing hollow cutouts

### ISSUE THREAD

**Issue by plut0nium** [jaseg/gerbolyze#11]
I am trying to use svg-flatten to convert SVG images to kicad footprints (silkscreen graphics).
My drawings contain multiple closed shapes with cutouts but these are rendered as plain filled areas, here are original image from inkscape and result in kicad:
![original_image](https://user-images.githubusercontent.com/2298861/108128846-ab44d480-70ad-11eb-9cb2-b62ffb3968f6.png)
![kicad_result](https://user-images.githubusercontent.com/2298861/108128583-3f626c00-70ad-11eb-8c1d-a039b48dd2e7.png)

Am I missing something or do I need specific preparation of the SVG file ?

The command line I use is:
`svg-flatten --format kicad --sexp-layer F.SilkS --sexp-mod-name tentacles_02 tentacles2.svg ../pcb/drawings.pretty/tentacles_02.kicad_mod`

Thank you very much 😀

**Comment by neinseg** [comment]
Thank you for the report! Would you mind sharing the input SVG file with me at github@jaseg.de? This should work, so chances are you've found a bug.

**Comment by neinseg** [comment]
Thank you for the test file. I have had a look and your problem should be fixed in v2.0.6, now on the main branch and on pypi.

The underlying issue was that your SVG for some reason contained only open paths and no closed paths at all. In SVG, an open path is one whose two ends are not connected, like the shape of the letter "C" vs. "O". In SVG, filling open subpaths like that is still well-defined behavior ([spec](https://www.w3.org/TR/SVG/painting.html#SpecifyingFillPaint)) even though here it likely is not what you want since when setting a stroke, things will look weird around the spot where the two ends of the path are.

Gerbolyze now handles this case according to spec and the resulting kicad_mod looks as you would expect. Please check it out, and feel free to re-open this issue or to open another issue should it not work as expected.
