### ISSUE TITLE
very cool!

### ISSUE THREAD

**Issue by badgeek** [jaseg/gerbolyze#3]
thanks! this is what i always want to do with svg2sz but have no time and clue, im looking a way to integrate to svg2sz...

**Comment by jaseg** [comment]
Thanks :)

The 'cool' way to integrate this into svg2sz would be to use it for bitmap graphics embedded into SVG files. The core logic is based on opencv and is pretty simple so it shouldn't be too much trouble to port it to C/C++ and emit KiCAD primitives instead of Gerber primitives. The main issue I see there is that KiCAD might not like that many primitives at once and just get slow, but I haven't tried.

If you need any help understanding the code feel free to ask.

**Comment by neinseg** [comment]
@badgeek have a look at version 2, now on the main branch: Gerbolyze has now learned to both read SVG with almost full spec support and it can now generate kicad_mod files from arbitrary svg input by doing some funky (and a bit slow) computer geometry. The old code for tracing bitmaps is still there, but I have added some new fancy halftone processors for grayscale images as well.

Feel free to yoink anything you need :) The main geometry core and SVG parsing foo is in the [svg-flatten dir](https://github.com/jaseg/gerbolyze/tree/main/svg-flatten/src)

SVG example:
![](https://raw.githubusercontent.com/jaseg/gerbolyze/main/pics/test_svg_readme_composited.png)

Halftone processing example (left is output zoomed out, right is zoomed in):
![](https://raw.githubusercontent.com/jaseg/gerbolyze/main/pics/vec_poisson_composited.png)

**Comment by bakroistvan** [comment]
really nice
