### ISSUE TITLE
svg-flatten stuck on gerbolyze::dehole_polytree()

### ISSUE THREAD

**Issue by Altomare** [jaseg/gerbolyze#43]
Hi,

When trying to generate gerbers from SVGs for internal PCB layers, I had a case of svg-flatten being stuck forever.
I edited the shape in Inkscape, and I trimmed in order to get the simplest shape that causes the issue.

Looking at the code, it seems gerbolyze::dehole_polytree() is stuck in an infinite loop.
I tried debugging further but I need to familiarize myself more with that code at the moment.

**Version used:** Local build of 3.1.5

**Command:**
`svg-flatten --format gerber -f flatten_stuck.svg /tmp/test.gbr`

**flatten_stuck.svg**
```svg
<?xml version="1.0" encoding="UTF-8" standalone="no"?>

<svg
   version="1.1"
   id="Calque_1"
   x="0px"
   y="0px"
   width="88.567993"
   height="44.890415"
   viewBox="0 0 88.567993 44.890416"
   enable-background="new 0 0 829.5 1018.667"
   xml:space="preserve"
   sodipodi:docname="flatten_stuck.svg"
   inkscape:version="1.1.2 (0a00cf5339, 2022-02-04)"
   xmlns:inkscape="http://www.inkscape.org/namespaces/inkscape"
   xmlns:sodipodi="http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd"
   xmlns="http://www.w3.org/2000/svg"
   xmlns:svg="http://www.w3.org/2000/svg">
<g
   opacity="0.5"
   id="g8183"
   transform="translate(-171.84351,-49.776241)"><path
   id="path8181"
   d="m 260.4115,92.716241 v -42.94 l -87.98708,1.369466 c -7.16052,53.374633 53.58638,43.46921 87.98708,41.570534 z M 186.499,86.183 c -1.09,0 -1.98,-0.89 -1.98,-1.98 0,-1.1 0.89,-1.99 1.98,-1.99 1.1,0 1.99,0.89 1.99,1.99 0,1.09 -0.89,1.98 -1.99,1.98 z m 65,0 c -1.09,0 -1.98,-0.89 -1.98,-1.98 0,-1.1 0.89,-1.99 1.98,-1.99 1.1,0 1.99,0.89 1.99,1.99 0,1.09 -0.89,1.98 -1.99,1.98 z"/>
</g>
</svg>
```

Edit: removed the attachment and copied the SVG contents

**Comment by fstark** [comment]
The problem seems to be that ``dehole_polytree_worker`` "viable cut" is not viable: at a moment, the first segment of your first hole is pretty much on the border of the outer path, and the ``ctIntersection`` call returns an empty intersection.

At that moment, the algorithm stop making progress.

I don't know how to properly fix that, but checking if the intersection is empty and chosing a different segment seems to work. I am completely unfamiliar with the library, so the following code is very inefficient and computes the ctDifference and the ctIntersection twice.

`diff --git a/svg-flatten/src/svg_geom.cpp b/svg-flatten/src/svg_geom.cpp
index a36c881..c8477fa 100644
--- a/svg-flatten/src/svg_geom.cpp
+++ b/svg-flatten/src/svg_geom.cpp
@@ -112,24 +112,38 @@ static void dehole_polytree_worker(PolyNode &ptree, Paths &out, queue<PolyTree>
             out.push_back(nod->Contour);
 
         } else {
-            /* Do not add children's children, those were handled in the recursive call above */
-            Clipper c;
-            c.AddPath(nod->Contour, ptSubject, /* closed= */ true);
-            for (int k=0; k<nod->ChildCount(); k++) {
-                c.AddPath(nod->Childs[k]->Contour, ptSubject, /* closed= */ true);
-            }
 
-            /* Find a viable cut: Cut from top-left bounding box corner, through two subsequent points on the hole
-             * outline and to top-right bbox corner. */
-            IntRect bbox = c.GetBounds();
-            Path tri = { { bbox.left, bbox.top }, nod->Childs[0]->Contour[0], nod->Childs[0]->Contour[1], { bbox.right, bbox.top } };
-            c.AddPath(tri, ptClip, true);
-
-            c.StrictlySimple(true);
-            /* Execute twice, once for intersection fragment and once for difference fragment. Note that this will yield
-             * at least two, but possibly more polygons. */
-            c.Execute(ctDifference, todo.emplace(), pftNonZero);
-            c.Execute(ctIntersection, todo.emplace(), pftNonZero);
+            for (int ix=0;ix!=nod->Childs[0]->Contour.size();ix++)
+            {
+                /* Do not add children's children, those were handled in the recursive call above */
+                Clipper c;
+                c.AddPath(nod->Contour, ptSubject, /* closed= */ true);
+                for (int k=0; k<nod->ChildCount(); k++) {
+                    c.AddPath(nod->Childs[k]->Contour, ptSubject, /* closed= */ true);
+                }
+
+                /* Find a viable cut: Cut from top-left bounding box corner, through two subsequent points on the hole
+                * outline and to top-right bbox corner. */
+                IntRect bbox = c.GetBounds();
+                Path tri = { { bbox.left, bbox.top }, nod->Childs[0]->Contour[ix], nod->Childs[0]->Contour[ix+1], { bbox.right, bbox.top } };
+                c.AddPath(tri, ptClip, true);
+
+                c.StrictlySimple(true);
+                /* Execute twice, once for intersection fragment and once for difference fragment. Note that this will yield
+                * at least two, but possibly more polygons. */
+                PolyTree p0;
+                PolyTree p1;
+                c.Execute(ctDifference, p0, pftNonZero);// no progress?
+                c.Execute(ctIntersection, p1, pftNonZero);
+
+                if (p1.GetFirst() )
+                {       //  We got an intersection, se we made progress
+                    c.Execute(ctDifference, todo.emplace(), pftNonZero);// no progress?
+                    c.Execute(ctIntersection, todo.emplace(), pftNonZero);
+                    return ;
+                }
+                //  let's try with the next segment of the first hole
+            }
         }
     }
 }
`

**Comment by fstark** [comment]
Above patch doesn't fully work because I missed the outer loop (so the return skips part of the contour).

However, by cutting to the center of the holes, we get something that works

```diff
diff --git a/svg-flatten/src/svg_geom.cpp b/svg-flatten/src/svg_geom.cpp
index a36c881..040bbc4 100644
--- a/svg-flatten/src/svg_geom.cpp
+++ b/svg-flatten/src/svg_geom.cpp
@@ -119,10 +119,17 @@ static void dehole_polytree_worker(PolyNode &ptree, Paths &out, queue<PolyTree>
                 c.AddPath(nod->Childs[k]->Contour, ptSubject, /* closed= */ true);
             }
 
-            /* Find a viable cut: Cut from top-left bounding box corner, through two subsequent points on the hole
-             * outline and to top-right bbox corner. */
+            /* Find a viable cut: Cut from top-left bounding box corner to the horizontal middle of the first hole, down to the bottom and back to the bottom-left */
             IntRect bbox = c.GetBounds();
-            Path tri = { { bbox.left, bbox.top }, nod->Childs[0]->Contour[0], nod->Childs[0]->Contour[1], { bbox.right, bbox.top } };
+
+            cInt sumx = 0;
+            for (auto &v:nod->Childs[0]->Contour)
+            {
+                sumx += v.X;
+            }
+            sumx /= nod->Childs[0]->Contour.size();
+
+            Path tri = { { bbox.left, bbox.top }, { sumx, bbox.top }, { sumx,bbox.bottom }, {bbox.left, bbox.bottom} };
             c.AddPath(tri, ptClip, true);
 
             c.StrictlySimple(true);
@@ -130,6 +137,9 @@ static void dehole_polytree_worker(PolyNode &ptree, Paths &out, queue<PolyTree>
              * at least two, but possibly more polygons. */
             c.Execute(ctDifference, todo.emplace(), pftNonZero);
             c.Execute(ctIntersection, todo.emplace(), pftNonZero);
+
+            if (!todo.back().GetFirst())
+                printf( "***** ERROR INTERSECTION EMPTY *****\n" );
         }
     }
 }
```

I also added a message in case of empty intersection -- which was the original infinite loop issue.

**Comment by jaseg** [comment]
Thank y'all for the bug report and the suggested fix! I have pushed a fix to main, which will land in a release in the coming weeks.

In the end, the fix was a bit more complicated than suggested by @fstark. The infinite loop did not come from empty polytrees being pushed to the stack, as those would just be discarded by the next worker call. Instead, the infinite loop arose from the worker ceasing to make progress under particular circumstances: It would get a polytree with one hole in, and push a new polytree with the same hole back on the stack.

The issue ended up being the construction of the "tool" polygon. This was supposed to be a convex polygon, with two points at the top left and right corners of the bounding box, and two corners at the ends of an arbitrary segment of the hole's outline polygon. The issue with this was that during construction, the orientation of that hole outline segment was never checked, and so it could happen that sometimes, it would create a hourglass-shaped tool polygon with a big, fat self-intersection close to the hole. If at the same time we were unlucky enough for clipper to return the hole polygon with its first outline point in the same spot as during our last call, that would lead to this infinite loop.

The fix ended up being pretty simple: We just look through the hole polygon's outline segments until we find one that is not exactly vertical, and orient it to make sure we don't get a self-intersection.

The remaining TODO is to add a regression test for this.
